[package]
name = "rush"
version = "0.1.2"
authors = ["n01e0 <noleo@vanillabeans.mobi>"]
edition = "2018"

[dependencies]
colored = "1.9"
clap = "2.33"
dirs = "2.0.2"
signal-simple = "*"
hostname = "*"
